import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Link } from "@tanstack/react-router";
import {
  ArrowLeft,
  Award,
  Building2,
  Calendar,
  CheckCircle2,
  Copy,
  MapPin,
  Shield,
  TrendingUp,
} from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { PageLayout } from "../components/PageLayout";
import { ProtectedRoute } from "../components/ProtectedRoute";
import { ScoreGauge } from "../components/ScoreGauge";
import { useAppContext } from "../hooks/useAppContext";
import {
  calculateBusinessHealth,
  calculateLenderConfidence,
  formatCurrency,
  getTraditionalScoreLabel,
  getTraditionalScoreTier,
} from "../lib/scoring";
import { getCashflow, getCreditScore, getProfile } from "../lib/store";
import type {
  BusinessHealthData,
  BusinessProfile,
  CashflowData,
  CreditScore,
  LenderConfidenceData,
} from "../lib/types";

export function CreditPassportPage() {
  const { user } = useAppContext();
  const [profile, setProfile] = useState<BusinessProfile | null>(null);
  const [creditScore, setCreditScore] = useState<CreditScore | null>(null);
  const [_cashflow, setCashflow] = useState<CashflowData | null>(null);
  const [health, setHealth] = useState<BusinessHealthData | null>(null);
  const [confidence, setConfidence] = useState<LenderConfidenceData | null>(
    null,
  );

  useEffect(() => {
    if (!user) return;
    const p = getProfile(user.id);
    const s = getCreditScore(user.id);
    const c = getCashflow(user.id);
    setProfile(p);
    setCreditScore(s);
    setCashflow(c);
    if (p && s) {
      setHealth(calculateBusinessHealth(p, s, c));
      setConfidence(calculateLenderConfidence(p, s, c));
    }
  }, [user]);

  function handleCopyPassport() {
    if (!profile || !creditScore) return;
    const text = [
      "SME CREDIT PASSPORT",
      `Business: ${profile.businessName}`,
      `Location: ${profile.location}`,
      `Industry: ${profile.industry.replace("_", " ")}`,
      `Business Age: ${profile.businessAge} years`,
      "",
      "CREDIT SCORES",
      `Alt Score: ${creditScore.altScore}/900`,
      `Business Trust: ${creditScore.trustScore}/100`,
      creditScore.traditionalScore
        ? `CIBIL Score: ${creditScore.traditionalScore}/900`
        : "CIBIL Score: Not provided",
      `Risk Tier: ${creditScore.riskTier} Risk`,
      "",
      "FINANCIALS",
      `Monthly Revenue: ${formatCurrency(profile.monthlyRevenue)}`,
      `Monthly Expenses: ${formatCurrency(profile.monthlyExpenses)}`,
      `Net Margin: ${Math.round(((profile.monthlyRevenue - profile.monthlyExpenses) / profile.monthlyRevenue) * 100)}%`,
      "",
      "Generated by CredVist — credvist.ai",
    ].join("\n");
    navigator.clipboard.writeText(text).then(() => {
      toast.success("Passport copied to clipboard");
    });
  }

  const trustTier =
    creditScore?.trustScore != null
      ? creditScore.trustScore >= 70
        ? "Low"
        : creditScore.trustScore >= 40
          ? "Medium"
          : "High"
      : null;

  const netMargin =
    profile && profile.monthlyRevenue > 0
      ? Math.round(
          ((profile.monthlyRevenue - profile.monthlyExpenses) /
            profile.monthlyRevenue) *
            100,
        )
      : 0;

  return (
    <ProtectedRoute>
      <PageLayout>
        <div className="space-y-6 animate-fade-up max-w-2xl mx-auto">
          {/* Back */}
          <Link to="/dashboard">
            <button
              data-ocid="creditpassport.back.button"
              className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
              type="button"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
          </Link>

          {/* Header */}
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                <Award className="h-5 w-5 text-primary" />
              </div>
              <div>
                <h1 className="font-display text-2xl font-bold">
                  SME Credit Passport
                </h1>
                <p className="text-sm text-muted-foreground mt-0.5">
                  Your digital financial identity
                </p>
              </div>
            </div>
            {profile && creditScore && (
              <Button
                data-ocid="creditpassport.copy.button"
                variant="outline"
                size="sm"
                onClick={handleCopyPassport}
                className="shrink-0"
              >
                <Copy className="h-3.5 w-3.5 mr-1.5" />
                Copy
              </Button>
            )}
          </div>

          {/* Empty state */}
          {!profile && (
            <Card
              data-ocid="creditpassport.empty_state"
              className="border-dashed border-2"
            >
              <CardContent className="py-12 flex flex-col items-center gap-4 text-center">
                <Award className="h-10 w-10 text-muted-foreground" />
                <div>
                  <p className="font-semibold">No profile data</p>
                  <p className="text-sm text-muted-foreground mt-1">
                    Complete your business profile to generate your Credit
                    Passport
                  </p>
                </div>
                <Link to="/profile">
                  <button
                    data-ocid="creditpassport.profile.button"
                    className="text-sm text-primary hover:underline"
                    type="button"
                  >
                    Set up your profile →
                  </button>
                </Link>
              </CardContent>
            </Card>
          )}

          {/* Passport Card */}
          {profile && creditScore && (
            <>
              {/* Identity Header */}
              <Card
                data-ocid="creditpassport.identity.card"
                className="border-2 border-primary/20 bg-gradient-to-br from-primary/5 to-background"
              >
                <CardContent className="pt-6 pb-6">
                  <div className="flex items-start justify-between gap-4">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Building2 className="h-4 w-4 text-primary" />
                        <span className="font-display font-bold text-xl">
                          {profile.businessName}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <MapPin className="h-3.5 w-3.5" />
                        <span>{profile.location}</span>
                      </div>
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Calendar className="h-3.5 w-3.5" />
                        <span>{profile.businessAge} years in operation</span>
                      </div>
                      <Badge
                        variant="outline"
                        className="capitalize text-xs mt-1"
                      >
                        {profile.industry.replace("_", " ")}
                      </Badge>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">
                        Risk Level
                      </p>
                      <Badge
                        className={`text-sm px-3 py-1.5 border font-bold ${
                          creditScore.riskTier === "Low"
                            ? "score-low"
                            : creditScore.riskTier === "Medium"
                              ? "score-medium"
                              : "score-high"
                        }`}
                      >
                        {creditScore.riskTier} Risk
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* 3 Scores */}
              <div
                data-ocid="creditpassport.scores.panel"
                className="grid grid-cols-3 gap-3"
              >
                {/* Alt Score */}
                <Card className="flex flex-col items-center py-5">
                  <ScoreGauge
                    score={creditScore.altScore}
                    tier={creditScore.riskTier}
                    size="sm"
                  />
                  <p className="text-xs text-muted-foreground mt-2 text-center">
                    Alt Score
                  </p>
                  <p className="text-xs text-muted-foreground opacity-60">
                    300–900
                  </p>
                </Card>

                {/* Trust Score */}
                <Card className="flex flex-col items-center py-5 px-3">
                  <span className="font-display font-bold text-3xl">
                    {creditScore.trustScore}
                  </span>
                  <span className="text-xs text-muted-foreground">/100</span>
                  {trustTier && (
                    <Badge
                      className={`text-xs px-2 py-0.5 border mt-2 ${
                        trustTier === "Low"
                          ? "score-low"
                          : trustTier === "Medium"
                            ? "score-medium"
                            : "score-high"
                      }`}
                    >
                      {trustTier === "Low"
                        ? "High Trust"
                        : trustTier === "Medium"
                          ? "Moderate"
                          : "Low Trust"}
                    </Badge>
                  )}
                  <p className="text-xs text-muted-foreground mt-1 text-center">
                    Trust Score
                  </p>
                </Card>

                {/* CIBIL / Traditional */}
                <Card className="flex flex-col items-center py-5 px-3">
                  {creditScore.traditionalScore ? (
                    <>
                      <span className="font-display font-bold text-3xl">
                        {creditScore.traditionalScore}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        /900
                      </span>
                      <Badge
                        className={`text-xs px-2 py-0.5 border mt-2 ${
                          getTraditionalScoreTier(
                            creditScore.traditionalScore,
                          ) === "Low"
                            ? "score-low"
                            : getTraditionalScoreTier(
                                  creditScore.traditionalScore,
                                ) === "Medium"
                              ? "score-medium"
                              : "score-high"
                        }`}
                      >
                        {getTraditionalScoreLabel(creditScore.traditionalScore)}
                      </Badge>
                    </>
                  ) : (
                    <span className="text-2xl font-display font-bold text-muted-foreground">
                      —
                    </span>
                  )}
                  <p className="text-xs text-muted-foreground mt-1 text-center">
                    CIBIL Score
                  </p>
                </Card>
              </div>

              {/* Financial Metrics */}
              <Card data-ocid="creditpassport.financials.card">
                <CardContent className="pt-5 pb-5">
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
                    Financial Snapshot
                  </p>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                    {[
                      {
                        label: "Monthly Revenue",
                        value: formatCurrency(profile.monthlyRevenue),
                      },
                      {
                        label: "Monthly Expenses",
                        value: formatCurrency(profile.monthlyExpenses),
                      },
                      {
                        label: "Net Margin",
                        value: `${netMargin}%`,
                        highlight: netMargin >= 20,
                      },
                      {
                        label: "GST Number",
                        value: `${profile.gstNumber.slice(0, 10)}...`,
                      },
                    ].map(({ label, value, highlight }) => (
                      <div key={label}>
                        <p className="text-xs text-muted-foreground">{label}</p>
                        <p
                          className={`font-display font-bold text-base mt-0.5 ${
                            highlight ? "text-score-low" : ""
                          }`}
                        >
                          {value}
                        </p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Health + Confidence side by side */}
              {health && confidence && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {/* Business Health */}
                  <Card data-ocid="creditpassport.health.card">
                    <CardContent className="pt-5 pb-5 space-y-3">
                      <div className="flex items-center gap-2">
                        <TrendingUp className="h-4 w-4 text-primary" />
                        <span className="font-semibold text-sm">
                          Business Health
                        </span>
                      </div>
                      <div className="flex items-end gap-2">
                        <span className="font-display font-bold text-4xl">
                          {health.score}
                        </span>
                        <span className="text-sm text-muted-foreground mb-1">
                          / 100
                        </span>
                      </div>
                      <Badge
                        className={`text-xs px-2.5 py-1 border font-semibold ${
                          health.status === "Strong"
                            ? "score-low"
                            : health.status === "Moderate"
                              ? "score-medium"
                              : "score-high"
                        }`}
                      >
                        {health.status}
                      </Badge>
                      <Progress value={health.score} className="h-2" />
                      <p className="text-xs text-muted-foreground">
                        {health.description}
                      </p>
                    </CardContent>
                  </Card>

                  {/* Lender Confidence */}
                  <Card data-ocid="creditpassport.confidence.card">
                    <CardContent className="pt-5 pb-5 space-y-3">
                      <div className="flex items-center gap-2">
                        <Shield className="h-4 w-4 text-primary" />
                        <span className="font-semibold text-sm">
                          Lender Confidence
                        </span>
                      </div>
                      <div className="flex items-end gap-2">
                        <span className="font-display font-bold text-4xl">
                          {confidence.score}
                        </span>
                        <span className="text-sm text-muted-foreground mb-1">
                          / 100
                        </span>
                        <span
                          className={`font-display font-bold text-2xl ml-1 ${
                            confidence.score >= 65
                              ? "text-score-low"
                              : confidence.score >= 50
                                ? "text-score-medium"
                                : "text-score-high"
                          }`}
                        >
                          Grade {confidence.grade}
                        </span>
                      </div>
                      <Progress value={confidence.score} className="h-2" />
                      <p className="text-xs text-muted-foreground">
                        {confidence.description}
                      </p>
                    </CardContent>
                  </Card>
                </div>
              )}

              {/* Trust Indicators */}
              <Card data-ocid="creditpassport.trust.card">
                <CardContent className="pt-5 pb-5">
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
                    Trust Indicators
                  </p>
                  <div className="space-y-2">
                    {[
                      {
                        label: "GST Registered Business",
                        pass: !!profile.gstNumber,
                      },
                      {
                        label: "Business Age Verified",
                        pass: profile.businessAge > 0,
                      },
                      {
                        label: "Expense Ratio Healthy (<70%)",
                        pass:
                          profile.monthlyRevenue > 0 &&
                          profile.monthlyExpenses / profile.monthlyRevenue <
                            0.7,
                      },
                      {
                        label: "Revenue Meets Credit Threshold",
                        pass: profile.monthlyRevenue >= 100000,
                      },
                      {
                        label: "Positive Net Margin",
                        pass: profile.monthlyRevenue > profile.monthlyExpenses,
                      },
                      {
                        label: "No Fraud Flags",
                        pass: !creditScore.fraudFlag,
                      },
                    ].map(({ label, pass }) => (
                      <div
                        key={label}
                        className="flex items-center justify-between"
                      >
                        <span className="text-sm">{label}</span>
                        <Badge
                          className={`text-xs px-2 py-0.5 border ${
                            pass ? "score-low" : "score-high"
                          }`}
                        >
                          {pass ? (
                            <span className="flex items-center gap-1">
                              <CheckCircle2 className="h-3 w-3" /> Pass
                            </span>
                          ) : (
                            "Fail"
                          )}
                        </Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      </PageLayout>
    </ProtectedRoute>
  );
}
