// Stub backend type declarations — generated by build pipeline
export type backendInterface = {
  _initializeAccessControlWithSecret: (token: string) => Promise<void>;
};

export type CreateActorOptions = {
  agentOptions?: Record<string, unknown>;
  [key: string]: unknown;
};

export declare class ExternalBlob {
  static fromURL(url: string): ExternalBlob;
  getBytes(): Promise<Uint8Array>;
  onProgress?: (progress: number) => void;
}

export declare function createActor(
  canisterId: string,
  uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  downloadFile: (bytes: Uint8Array) => Promise<ExternalBlob>,
  options?: CreateActorOptions,
): backendInterface;
