// Stub backend — generated by build pipeline when Motoko canister is compiled

export type backendInterface = {
  _initializeAccessControlWithSecret: (token: string) => Promise<void>;
};

export type CreateActorOptions = {
  agentOptions?: Record<string, unknown>;
  [key: string]: unknown;
};

export class ExternalBlob {
  static fromURL(_url: string): ExternalBlob {
    return new ExternalBlob();
  }
  async getBytes(): Promise<Uint8Array> {
    return new Uint8Array();
  }
  onProgress?: (progress: number) => void;
}

export function createActor(
  _canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (bytes: Uint8Array) => Promise<ExternalBlob>,
  _options?: CreateActorOptions,
): backendInterface {
  return {
    _initializeAccessControlWithSecret: async () => {},
  };
}

export default createActor;
